language: python
sudo: false
matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=py27
    - python: "3.5"
      env: TOX_ENV=py35
    - python: "3.6"
      env: TOX_ENV=py36
    - python: "pypy2.7-5.8.0"
      env: TOX_ENV=pypy
    - python: "2.7"
      env: TOX_ENV=analysis
    - python: "2.7"
      env: TOX_ENV=coverage
install:
 - pip install tox
 - pip install coveralls
script:
 - tox -e $TOX_ENV
after_success:
 - if [[ $TOX_ENV = "coverage" ]]; then coveralls; fi
